module ums {
  export interface FeeResponseType {
    ADMITTED: string;
    APPLIED: string;
    ALLOWED: string;
    NOT_ALLOWED: string;
    NOT_WITHIN_SLOT: string;
    INSTALLMENT_AVAILABLE: string;
    INSTALLMENT_NOT_AVAILABLE: string;
    FIRST_INSTALLMENT_PAID: string;
    INSTALLMENT_NOT_TAKEN: string;
    READMISSION_APPLIED: string;
    READMISSION_NOT_APPLIED: string;
    REGULAR_ADMISSION: string;
  }

  export class SemesterFeeResponse {
    public static responseType: FeeResponseType = {
      ADMITTED: "ADMITTED",
      APPLIED: "APPLIED",
      ALLOWED: "ALLOWED",
      NOT_ALLOWED: "NOT_ALLOWED",
      NOT_WITHIN_SLOT: "NOT_WITHIN_SLOT",
      INSTALLMENT_AVAILABLE: "INSTALLMENT_AVAILABLE",
      INSTALLMENT_NOT_AVAILABLE: "INSTALLMENT_NOT_AVAILABLE",
      FIRST_INSTALLMENT_PAID: "FIRST_INSTALLMENT_PAID",
      INSTALLMENT_NOT_TAKEN: "INSTALLMENT_NOT_TAKEN",
      READMISSION_APPLIED: "READMISSION_APPLIED",
      READMISSION_NOT_APPLIED: "READMISSION_NOT_APPLIED",
      REGULAR_ADMISSION: "REGULAR_ADMISSION"
    }
  }
}
