package org.ums.enums.common;

import java.util.EnumSet;
import java.util.HashMap;
import java.util.Map;

/**
 * Created by Monjur-E-Morshed on 18-May-17.
 */
public enum DesignationType {
  LECTURER(104, "LECTURER"),
  ASSISTANT_PROFESSOR(103, "ASSISTANT PROFESSOR"),
  ASSOCIATE_PROFESSOR(102, "ASSOCIATE PROFESSOR"),
  PROFESSOR(101, "PROFESSOR"),
  REGISTRAR(201, "REGISTRAR"),
  CONTROLLER_OF_EXAMINATIONS(202, "CONTROLLER OF EXAMINATIONS"),
  UNIVERSITY_ENGINEER(203, "UNIVERSITY ENGINEER"),
  LIBRARIAN(204, "LIBRARIAN"),
  DEPUTY_REGISTRAR(211, "DEPUTY REGISTRAR"),
  DEPUTY_CONTROLLER_OF_EXAMINATIONS(212, "DEPUTY CONTROLLER OF EXAMINATIONS"),
  EXECUTIVE_ENGINEER(213, "EXECUTIVE ENGINEER"),
  DEPUTY_LIBRARIAN(214, "DEPUTY LIBRARIAN"),
  ASSISTANT_REGISTRAR(221, "ASSISTANT REGISTRAR"),
  ASSISTANT_CONTROLLER_OF_EXAMINATIONS(222, "ASSISTANT CONTROLLER OF EXAMINATIONS"),
  ASSISTANT_DIRECTOR_OF_ACCOUNTS(223, "ASSISTANT DIRECTOR OF ACCOUNTS"),
  ASSISTANT_LIBRARIAN(224, "ASSISTANT LIBRARIAN"),
  SYSTEM_ENGINEER(225, "SYSTEM ENGINEER"),
  MEDICAL_OFFICER(226, "MEDICAL OFFICER"),
  SECTION_OFFICER(231, "SECTION OFFICER"),
  ADMIN_OFFICER(241, "ADMIN OFFICER"),
  ASSISTANT_ADMIN_OFFICER(251, "ASSISTANT ADMIN OFFICER"),
  PUBLICATION_CUM_INFORMATION_OFFICER(252, "PUBLICATION CUM INFORMATION OFFICER"),
  ASSISTANT_ACCOUNT_OFFICER(253, "ASSISTANT ACCOUNT OFFICER"),
  SUB_ASSISTANT_ENGINEER(254, "SUB-ASSISTANT ENGINEER"),
  ASSISTANT_FOREMAN_INSTRUCTOR(255, "ASSISTANT FOREMAN INSTRUCTOR"),
  CATALOGER(301, "CATALOGER"),
  LIBRARY_ASSISTANT(302, "LIBRARY ASSISTANT"),
  COMPUTER_COMPOSER(303, "COMPUTER COMPOSER"),
  SR_WORKS_SARKER(304, "SR. WORKS SARKER"),
  LABORATORY_ASSISTANT(305, "LABORATORY ASSISTANT"),
  CRAFT_INSTRUCTOR(306, "CRAFT INSTRUCTOR"),
  BOOK_SORTER(307, "BOOK SORTER"),
  U_D_a(308, "U.D.A"),
  ELECTRICIAN(309, "ELECTRICIAN"),
  WEB_SITE_TECHNICIAN(310, "WEB-SITE TECHNICIAN"),
  PHOTOCOPY_TECHNICIAN(311, "PHOTOCOPY TECHNICIAN"),
  DRIVER(312, "DRIVER"),
  LDA(321, "LDA"),
  LDA_CUM_TYPIST(322, "LDA CUM TYPIST"),
  LIBRARY_ATTENDANT(323, "LIBRARY ATTENDANT"),
  PEON(331, "PEON"),
  LIFT_OPERATOR(332, "LIFT OPERATOR"),
  MLSS(333, "MLSS"),
  VICE_CHANCELLOR(999, "VICE-CHANCELLOR"),
  TREASURER(888, "TREASURER");

  private String label;
  private int id;

  private DesignationType(int id, String label) {
    this.id = id;
    this.label = label;
  }

  private static final Map<Integer, DesignationType> lookup = new HashMap<>();

  static {
    for(DesignationType c : EnumSet.allOf(DesignationType.class)) {
      lookup.put(c.getId(), c);
    }
  }

  public static DesignationType get(final int pId) {
    return lookup.get(pId);
  }

  public String getLabel() {
    return this.label;
  }

  public int getId() {
    return this.id;
  }
}
