version: "3"
services:
  ums-solr:
    image: solr:5.5
    ports:
      - "8983:8983"
    environment:
      - SOLR_HOME=/opt/mysolrhome
      - SOLR_OPTS=-Dsolr.lock.type=single
    volumes:
      - //mnt/nfsshare/iums-solr:/opt/mysolrhome
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - ums
    networks:
      ums-net:
        aliases:
          - ums-solr
  ums-memcached:
    image: harrenhall:5001/ums-memcached
    ports:
      - "11211:11211"
    networks:
      ums-net:
        aliases:
          - ums-memcached
  ums-webservice-academic:
    image: harrenhall:5001/ums-webservice-academic:${TAG}
    volumes:
      - //mnt/nfsshare/ums/mapdb:/opt/mapdb
    deploy:
      replicas: 5
    networks:
      ums-net:
        aliases:
          - ums-webservice-academic
  ums-webservice-library:
      image: harrenhall:5001/ums-webservice-library:${TAG}
      volumes:
        - //mnt/nfsshare/ums/mapdb:/opt/mapdb
      deploy:
        replicas: 5
      networks:
        ums-net:
          aliases:
            - ums-webservice-library
  ums-webservice-registrar:
      image: harrenhall:5001/ums-webservice-registrar:${TAG}
      volumes:
        - //mnt/nfsshare/ums/mapdb:/opt/mapdb
      deploy:
        replicas: 5
      networks:
        ums-net:
          aliases:
            - ums-webservice-registrar
  ums-webservice-bank:
      image: harrenhall:5001/ums-webservice-bank:${TAG}
      deploy:
        replicas: 5
      volumes:
        - //mnt/nfsshare/ums/mapdb:/opt/mapdb
      networks:
        ums-net:
          aliases:
            - ums-webservice-bank
  ums-webservice-account:
      image: harrenhall:5001/ums-webservice-account:${TAG}
      deploy:
        replicas: 5
      volumes:
        - //mnt/nfsshare/ums/mapdb:/opt/mapdb
      networks:
        ums-net:
          aliases:
            - ums-webservice-account
  ums-web:
    image: harrenhall:5001/ums-web:${TAG}
    ports:
      - "80:80"
    networks:
      ums-net:
        aliases:
          - ums-web
  ums-microservice-cache-warmer:
    image: harrenhall:5001/ums-microservice-cache-warmer:${TAG}
    networks:
      ums-net:
        aliases:
          - ums-microservice-cache-warmer
  ums-microservice-indexer:
    image: harrenhall:5001/ums-microservice-indexer:${TAG}
    networks:
      ums-net:
        aliases:
          - ums-microservice-indexer
  visualizer:
    image: dockersamples/visualizer:stable
    environment:
      - CTX_ROOT=/visualizer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      ums-net:
        aliases:
          - visualizer
networks:
  ums-net:

volumes:
  ums-datavolume:
    external: true
