DROP TABLE DB_IUMS.BEARER_ACCESS_TOKEN CASCADE CONSTRAINTS;

CREATE TABLE DB_IUMS.BEARER_ACCESS_TOKEN
(
  USER_ID           VARCHAR2(30 BYTE),
  TOKEN             VARCHAR2(150 BYTE)          NOT NULL,
  LAST_ACCESS_TIME  DATE,
  LAST_MODIFIED     VARCHAR2(18 BYTE),
  REFRESH_TOKEN     VARCHAR2(150 BYTE)
)
