version: "2"
services:
  oraclexe:
    image: sath89/oracle-xe-11g
    ports:
    - "15080:8080"
    - "1522:1521"
    volumes:
    - "/home/munna/Music/ums_src/UMS/ums-dist/src/main/resources/misc/database/oradata:/u01/app/oracle"
    - "/home/munna/Pictures:/home"

