CREATE TABLE EMP_EL_BALANCE(
  ID NUMBER NOT NULL,
  EMPLOYEE_ID VARCHAR2(8),
  FULL_PAY NUMBER,
  HALF_PAY NUMBER,
  CREATED_ON DATE,
  UPDATED_ON DATE,
  LAST_MODIFIED VARCHAR2(18),
  PRIMARY KEY (ID)
);


CREATE TABLE EMP_EL_HISTORY(
  ID NUMBER NOT NULL,
  DESCRIPTION VARCHAR2(25) NOT NULL,
  DATE DATE,
  DEBIT NUMBER,
  CREDIT NUMBER,
  BALANCE NUMBER,
  BALANCE_TYPE NUMBER,
  LAST_MODIFIED VARCHAR2(18),
  PRIMARY KEY (ID)
);



alter table LMS_TYPE
add category number;

alter table LMS_TYPE
add view_order number;

alter table lms_type
add visibility number;