alter table student_Record add GRADESHEET_REMARKS       VARCHAR2(500 BYTE),
  TABULATIONSHEET_REMARKS  VARCHAR2(500 BYTE);
/

ALTER TABLE DB_IUMS.STUDENT_RECORD_CURR
MODIFY(GPA NUMBER(7,6))
/


ALTER TABLE DB_IUMS.STUDENT_RECORD_CURR
MODIFY(CGPA NUMBER(7,6))
/
