version: "3"
services:
  ums-jenkins:
    image: harrenhall:5001/ums-jenkins
    user: root
    ports:
      - "81:8080"
      - "50000:50000"
    volumes:
      - //mnt/nfsshare/iums-jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
